system:
  base-url: "http://localhost:8080" # 后端服务公网访问地址，用于生成导出文件的完整下载链接

mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: ai_study_assistant
  username: root
  password: your_database_password
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "error"

jwt:
  signing-key: "your_jwt_secret_key"
  expires-time: 7200
  refresh-expires-time: 1209600
  buffer-time: 86400
  issuer: "ai-study-assistant"

redis:
  db: 0
  addr: "localhost:6379"
  password: "your_redis_password"

email:
  from: "your_email@example.com"
  nickname: "AI Study Assistant"
  secret: "your_email_smtp_secret"
  host: "smtp.example.com"
  port: 465
  is-ssl: true

log:
  enabled: true
  level: "info"
  format: "console"
  output-paths:
    - "stdout"
  error-output-paths:
    - "stderr"
  disable-caller: false
  disable-stacktrace: false

ai:
  base-url: "https://api.siliconflow.cn/v1"
  api-key: "your_ai_api_key_here"
  model: "Pro/moonshotai/Kimi-K2.5"
  allow-intranet-fetch: false
  allow-localhost-fetch: false

qiniu:
  access-key: "your_qiniu_access_key"
  secret-key: "your_qiniu_secret_key"
  bucket: "your_bucket_name"
  domain: "your_bucket_domain"
  zone: "your_bucket_zone"
