package main

import (
"fmt"
"gorm.io/driver/mysql"
"gorm.io/gorm"
)

type Message struct {
ID      int64  gorm:"primaryKey;autoIncrement"
Content string
}

func main() {
    // using a dummy dsn, we just want to see the SQL generated by DryRun
db, err := gorm.Open(mysql.Open("dummy:dummy@tcp(127.0.0.1:3306)/dummy"), &gorm.Config{
        DryRun: true,
    })
if err != nil {
panic(err)
}

    stmt := db.Unscoped().Where("id IN ?", []int64{1, 2}).Delete(&Message{}).Statement
    fmt.Println(stmt.SQL.String())
}
